n = input('Digite um valor: ')
print("É um numero ou não ?",n.isnumeric())
print('É uma letra ou nao ?', n.isalpha())
print('É alpha numerico ?', n.isalnum())
print('Esta somente com letra MAIUSCULAS ?', n.isupper())