nome = str(input("Digite seu nome: ")).strip()
print(f"Analisando seu nome...")
print(f"Seu nome em MAIUSCULAS é {nome.upper()}")
print(f"Seu nome em minusculas é {nome.lower()}")
print(f"Seu nome tem ao todo {len(nome)- nome.count(' ')}")
print(f"Seu primeiro nome tem {nome.find(' ')}")
separa = nome.split()
print(separa)
print(f"Seu primeiro nome é {separa[0]}, tem {len(separa[0])} letras")