n1 = int(input('Digite um numero: '))
n2 = int(input('Digite outro numero: '))
n3 = int(input('Digite um numero: '))
n4 = int(input('Digite outro numero: '))
#n5 = int(input('Digite outro numero: '))
#s = n1 * n2 + n3 ** n4
a = n1 * (n2 + n3) ** n4
#print(f'O resultado de {n1} * {n2} + {n3} ** {n4} é = {s}')
print(f'O resultado de {n1} * ({n2} + {n3}) ** {n4} é = {a}')