# Generated by Django 4.2.4 on 2023-08-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite_project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
